###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID eltonsilva)
#  Generated on:      Thu May 22 13:25:12 2025
#  Design:            rom
#  Command:           create_clock_tree_spec -out_file ../scripts/cts.spec
###############################################################
