/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID eltonsilva)
#  Generated on:      Thu May 22 15:23:27 2025
#  Design:            rom
#  Command:           write_netlist ../deliverables/rom_layout.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: May 22 2025 14:01:39 -03 (May 22 2025 17:01:39 UTC)
// Verification Directory fv/rom 
module hdec (
	d_in, 
	d_out);
   input [38:0] d_in;
   output [31:0] d_out;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_134;
   wire n_135;

   XNOR2X1 g1979__2398 (.Y(d_out[31]),
	.A(d_in[38]),
	.B(n_135));
   XNOR2X1 g1980__5107 (.Y(d_out[26]),
	.A(d_in[33]),
	.B(n_134));
   XNOR2X1 g1981__6260 (.Y(d_out[2]),
	.A(d_in[6]),
	.B(n_115));
   XNOR2X1 g1982__4319 (.Y(d_out[27]),
	.A(d_in[34]),
	.B(n_117));
   XNOR2X1 g1983__8428 (.Y(d_out[29]),
	.A(d_in[36]),
	.B(n_116));
   CLKXOR2X1 g1984__5526 (.Y(d_out[30]),
	.A(d_in[37]),
	.B(n_119));
   CLKXOR2X1 g1985__6783 (.Y(d_out[28]),
	.A(d_in[35]),
	.B(n_118));
   XNOR2X1 g1986__3680 (.Y(d_out[0]),
	.A(d_in[3]),
	.B(n_88));
   XNOR2X1 g1987__1617 (.Y(d_out[4]),
	.A(d_in[9]),
	.B(n_106));
   XNOR2X1 g1988__2802 (.Y(d_out[8]),
	.A(d_in[13]),
	.B(n_108));
   XNOR2X1 g1989__1705 (.Y(d_out[6]),
	.A(d_in[11]),
	.B(n_107));
   XNOR2X1 g1990__5122 (.Y(d_out[1]),
	.A(d_in[5]),
	.B(n_105));
   XNOR2X1 g1991__8246 (.Y(d_out[19]),
	.A(d_in[25]),
	.B(n_113));
   XNOR2X1 g1992__7098 (.Y(d_out[10]),
	.A(d_in[15]),
	.B(n_109));
   XNOR2X1 g1993__6131 (.Y(d_out[11]),
	.A(d_in[17]),
	.B(n_103));
   XNOR2X1 g1994__1881 (.Y(d_out[23]),
	.A(d_in[29]),
	.B(n_95));
   XNOR2X1 g1995__5115 (.Y(d_out[21]),
	.A(d_in[27]),
	.B(n_94));
   XNOR2X1 g1996__7482 (.Y(d_out[7]),
	.A(d_in[12]),
	.B(n_93));
   OR3X1 g1997__4733 (.Y(n_135),
	.A(n_67),
	.B(n_71),
	.C(n_101));
   OR3X1 g1998__6161 (.Y(n_134),
	.A(n_68),
	.B(n_72),
	.C(n_114));
   CLKXOR2X1 g1999__9315 (.Y(d_out[16]),
	.A(d_in[22]),
	.B(n_112));
   XNOR2X1 g2000__9945 (.Y(d_out[3]),
	.A(d_in[7]),
	.B(n_98));
   XNOR2X1 g2001__2883 (.Y(d_out[18]),
	.A(d_in[24]),
	.B(n_102));
   XNOR2X1 g2002__2346 (.Y(d_out[25]),
	.A(d_in[31]),
	.B(n_92));
   XNOR2X1 g2003__1666 (.Y(d_out[9]),
	.A(d_in[14]),
	.B(n_89));
   XNOR2X1 g2004__7410 (.Y(d_out[15]),
	.A(d_in[21]),
	.B(n_91));
   XNOR2X1 g2005__6417 (.Y(d_out[13]),
	.A(d_in[19]),
	.B(n_90));
   XNOR2X1 g2006__5477 (.Y(d_out[22]),
	.A(d_in[28]),
	.B(n_100));
   XNOR2X1 g2007__2398 (.Y(d_out[20]),
	.A(d_in[26]),
	.B(n_99));
   XNOR2X1 g2008__5107 (.Y(d_out[17]),
	.A(d_in[23]),
	.B(n_97));
   XNOR2X1 g2009__6260 (.Y(d_out[14]),
	.A(d_in[20]),
	.B(n_111));
   XNOR2X1 g2010__4319 (.Y(d_out[12]),
	.A(d_in[18]),
	.B(n_110));
   XNOR2X1 g2011__8428 (.Y(d_out[24]),
	.A(d_in[30]),
	.B(n_104));
   XNOR2X1 g2012__5526 (.Y(d_out[5]),
	.A(d_in[10]),
	.B(n_96));
   NOR2X1 g2013__6783 (.Y(n_119),
	.A(n_73),
	.B(n_114));
   NOR2X1 g2014__3680 (.Y(n_118),
	.A(n_74),
	.B(n_114));
   OR2X1 g2015__1617 (.Y(n_117),
	.A(n_74),
	.B(n_101));
   OR2X1 g2016__2802 (.Y(n_116),
	.A(n_73),
	.B(n_101));
   OR3X1 g2017__1705 (.Y(n_115),
	.A(n_64),
	.B(n_76),
	.C(n_79));
   NAND2X1 g2018__5122 (.Y(n_113),
	.A(n_2),
	.B(n_82));
   NOR2X1 g2019__8246 (.Y(n_112),
	.A(n_1),
	.B(n_79));
   NAND2BX1 g2020__7098 (.Y(n_111),
	.AN(n_1),
	.B(n_84));
   NAND2BX1 g2021__6131 (.Y(n_110),
	.AN(n_1),
	.B(n_80));
   NAND2BX1 g2022__1881 (.Y(n_109),
	.AN(n_79),
	.B(n_0));
   NAND2X1 g2023__5115 (.Y(n_108),
	.A(n_0),
	.B(n_84));
   NAND2X1 g2024__7482 (.Y(n_107),
	.A(n_0),
	.B(n_80));
   NAND2X1 g2025__4733 (.Y(n_106),
	.A(n_0),
	.B(n_82));
   NAND2X1 g2026__6161 (.Y(n_105),
	.A(n_85),
	.B(n_84));
   OR2X1 g2027__9315 (.Y(n_104),
	.A(n_86),
	.B(n_79));
   NAND2X1 g2028__9945 (.Y(n_103),
	.A(n_81),
	.B(n_82));
   NAND2X1 g2029__2883 (.Y(n_102),
	.A(n_87),
	.B(n_82));
   NAND2X2 g2030__2346 (.Y(n_114),
	.A(n_52),
	.B(n_85));
   NAND2X1 g2031__1666 (.Y(n_100),
	.A(n_87),
	.B(n_84));
   NAND2X1 g2032__7410 (.Y(n_99),
	.A(n_87),
	.B(n_80));
   NAND2BX1 g2033__6417 (.Y(n_98),
	.AN(n_79),
	.B(n_85));
   NAND2BX1 g2034__5477 (.Y(n_97),
	.AN(n_79),
	.B(n_81));
   NAND2X1 g2035__2398 (.Y(n_96),
	.A(n_83),
	.B(n_80));
   NAND2X1 g2036__5107 (.Y(n_95),
	.A(n_2),
	.B(n_84));
   NAND2X1 g2037__6260 (.Y(n_94),
	.A(n_2),
	.B(n_80));
   NAND2X1 g2038__4319 (.Y(n_93),
	.A(n_83),
	.B(n_84));
   NAND2BX1 g2039__8428 (.Y(n_92),
	.AN(n_79),
	.B(n_2));
   NAND2X1 g2040__5526 (.Y(n_91),
	.A(n_81),
	.B(n_84));
   NAND2X1 g2041__6783 (.Y(n_90),
	.A(n_81),
	.B(n_80));
   NAND2BX1 g2042__3680 (.Y(n_89),
	.AN(n_79),
	.B(n_83));
   NAND2X1 g2043__1617 (.Y(n_88),
	.A(n_85),
	.B(n_80));
   OR3X1 g2044__2802 (.Y(n_101),
	.A(n_51),
	.B(n_64),
	.C(n_76));
   INVX2 g2045 (.Y(n_87),
	.A(n_86));
   NAND2X2 g2048__1705 (.Y(n_86),
	.A(n_64),
	.B(n_77));
   NOR2X2 g2049__5122 (.Y(n_85),
	.A(n_64),
	.B(n_75));
   NOR2X4 g2050__8246 (.Y(n_84),
	.A(n_52),
	.B(n_73));
   NOR2X2 g2051__7098 (.Y(n_83),
	.A(n_63),
	.B(n_76));
   AND3X1 g2053__6131 (.Y(n_82),
	.A(n_51),
	.B(n_67),
	.C(n_71));
   NOR2X2 g2054__1881 (.Y(n_81),
	.A(n_64),
	.B(n_78));
   NOR2X4 g2055__5115 (.Y(n_80),
	.A(n_52),
	.B(n_74));
   OR3X2 g2056__7482 (.Y(n_79),
	.A(n_52),
	.B(n_67),
	.C(n_71));
   OR2X1 g2059__4733 (.Y(n_78),
	.A(n_59),
	.B(n_69));
   NOR2X2 g2060__6161 (.Y(n_77),
	.A(n_59),
	.B(n_70));
   OR2X1 g2061__9315 (.Y(n_76),
	.A(n_58),
	.B(n_70));
   OR2X1 g2063__9945 (.Y(n_75),
	.A(n_58),
	.B(n_69));
   OR2X1 g2064__2883 (.Y(n_74),
	.A(n_67),
	.B(n_72));
   OR2X1 g2065__2346 (.Y(n_73),
	.A(n_68),
	.B(n_71));
   INVX2 g2066 (.Y(n_71),
	.A(n_72));
   XNOR2X1 g2067__1666 (.Y(n_72),
	.A(n_40),
	.B(n_66));
   INVX2 g2068 (.Y(n_69),
	.A(n_70));
   INVX2 g2069 (.Y(n_67),
	.A(n_68));
   XNOR2X1 g2070__7410 (.Y(n_70),
	.A(n_36),
	.B(n_62));
   XNOR2X1 g2071__6417 (.Y(n_68),
	.A(n_37),
	.B(n_65));
   XNOR2X1 g2072__5477 (.Y(n_66),
	.A(n_48),
	.B(n_60));
   XNOR2X1 g2073__2398 (.Y(n_65),
	.A(n_35),
	.B(n_61));
   INVX2 g2074 (.Y(n_64),
	.A(n_63));
   XNOR2X1 g2075__5107 (.Y(n_62),
	.A(n_34),
	.B(n_57));
   XNOR2X1 g2076__6260 (.Y(n_63),
	.A(n_42),
	.B(n_56));
   XNOR2X1 g2077__4319 (.Y(n_61),
	.A(n_32),
	.B(n_55));
   XNOR2X1 g2078__8428 (.Y(n_60),
	.A(d_in[36]),
	.B(n_54));
   INVX1 g2079 (.Y(n_58),
	.A(n_59));
   XNOR2X1 g2080__5526 (.Y(n_57),
	.A(n_17),
	.B(n_55));
   XNOR2X1 g2081__6783 (.Y(n_56),
	.A(n_45),
	.B(n_54));
   XNOR2X1 g2082__3680 (.Y(n_59),
	.A(n_47),
	.B(n_53));
   XNOR2X1 g2083__1617 (.Y(n_55),
	.A(n_41),
	.B(n_50));
   XNOR2X1 g2084__2802 (.Y(n_53),
	.A(n_9),
	.B(n_46));
   XNOR2X1 g2085__1705 (.Y(n_54),
	.A(n_11),
	.B(n_49));
   INVX1 g2086 (.Y(n_51),
	.A(n_52));
   XNOR2X1 g2087__5122 (.Y(n_50),
	.A(n_15),
	.B(n_43));
   XNOR2X1 g2088__8246 (.Y(n_49),
	.A(n_4),
	.B(n_38));
   XNOR2X2 g2089__7098 (.Y(n_52),
	.A(n_33),
	.B(n_44));
   XNOR2X1 g2090__6131 (.Y(n_48),
	.A(n_17),
	.B(n_39));
   XNOR2X1 g2091__1881 (.Y(n_47),
	.A(n_19),
	.B(n_39));
   XNOR2X1 g2092__5115 (.Y(n_46),
	.A(n_38),
	.B(n_45));
   XNOR2X1 g2093__7482 (.Y(n_44),
	.A(d_in[32]),
	.B(n_30));
   XNOR2X1 g2094__4733 (.Y(n_43),
	.A(d_in[23]),
	.B(n_22));
   XNOR2X1 g2095__6161 (.Y(n_42),
	.A(n_21),
	.B(n_31));
   XNOR2X1 g2096__9315 (.Y(n_41),
	.A(n_29),
	.B(n_18));
   XNOR2X1 g2097__9945 (.Y(n_40),
	.A(n_23),
	.B(n_32));
   XNOR2X1 g2098__2883 (.Y(n_45),
	.A(n_26),
	.B(n_27));
   XNOR2X1 g2099__2346 (.Y(n_37),
	.A(n_10),
	.B(n_25));
   XNOR2X1 g2100__1666 (.Y(n_36),
	.A(n_14),
	.B(n_13));
   XNOR2X1 g2101__7410 (.Y(n_35),
	.A(n_8),
	.B(n_7));
   XNOR2X1 g2102__6417 (.Y(n_34),
	.A(n_16),
	.B(n_12));
   XNOR2X1 g2103__5477 (.Y(n_33),
	.A(n_5),
	.B(n_20));
   XNOR2X1 g2104__2398 (.Y(n_39),
	.A(n_6),
	.B(n_28));
   XNOR2X1 g2105__5107 (.Y(n_38),
	.A(n_3),
	.B(n_24));
   XNOR2X1 g2106__6260 (.Y(n_31),
	.A(d_in[10]),
	.B(d_in[11]));
   XNOR2X1 g2107__4319 (.Y(n_30),
	.A(d_in[33]),
	.B(d_in[37]));
   XNOR2X1 g2108__8428 (.Y(n_29),
	.A(d_in[19]),
	.B(d_in[31]));
   XNOR2X1 g2109__5526 (.Y(n_28),
	.A(d_in[21]),
	.B(d_in[23]));
   XNOR2X1 g2110__6783 (.Y(n_27),
	.A(d_in[25]),
	.B(d_in[27]));
   XNOR2X1 g2111__3680 (.Y(n_26),
	.A(d_in[24]),
	.B(d_in[26]));
   XNOR2X1 g2112__1617 (.Y(n_25),
	.A(d_in[14]),
	.B(d_in[34]));
   XNOR2X1 g2113__2802 (.Y(n_24),
	.A(d_in[29]),
	.B(d_in[30]));
   XNOR2X1 g2114__1705 (.Y(n_23),
	.A(d_in[4]),
	.B(d_in[7]));
   XNOR2X1 g2115__5122 (.Y(n_22),
	.A(d_in[11]),
	.B(d_in[27]));
   XNOR2X1 g2116__8246 (.Y(n_21),
	.A(d_in[8]),
	.B(d_in[9]));
   XNOR2X1 g2117__7098 (.Y(n_20),
	.A(d_in[34]),
	.B(d_in[36]));
   XNOR2X1 g2118__6131 (.Y(n_19),
	.A(d_in[17]),
	.B(d_in[19]));
   XNOR2X1 g2119__1881 (.Y(n_18),
	.A(d_in[7]),
	.B(d_in[15]));
   XNOR2X1 g2120__5115 (.Y(n_32),
	.A(d_in[6]),
	.B(d_in[38]));
   XNOR2X1 g2121__7482 (.Y(n_16),
	.A(d_in[13]),
	.B(d_in[25]));
   XNOR2X1 g2122__4733 (.Y(n_15),
	.A(d_in[3]),
	.B(d_in[35]));
   XNOR2X1 g2123__6161 (.Y(n_14),
	.A(d_in[1]),
	.B(d_in[17]));
   XNOR2X1 g2124__9315 (.Y(n_13),
	.A(d_in[21]),
	.B(d_in[33]));
   XNOR2X1 g2125__9945 (.Y(n_12),
	.A(d_in[9]),
	.B(d_in[29]));
   XNOR2X1 g2126__2883 (.Y(n_11),
	.A(d_in[14]),
	.B(d_in[15]));
   XNOR2X1 g2127__2346 (.Y(n_10),
	.A(d_in[18]),
	.B(d_in[22]));
   XNOR2X1 g2128__1666 (.Y(n_9),
	.A(d_in[16]),
	.B(d_in[18]));
   XNOR2X1 g2129__7410 (.Y(n_8),
	.A(d_in[2]),
	.B(d_in[26]));
   XNOR2X1 g2130__6417 (.Y(n_7),
	.A(d_in[10]),
	.B(d_in[30]));
   XNOR2X1 g2131__5477 (.Y(n_6),
	.A(d_in[20]),
	.B(d_in[22]));
   XNOR2X1 g2132__2398 (.Y(n_5),
	.A(d_in[35]),
	.B(d_in[38]));
   XNOR2X1 g2133__5107 (.Y(n_4),
	.A(d_in[12]),
	.B(d_in[13]));
   XNOR2X1 g2134__6260 (.Y(n_3),
	.A(d_in[28]),
	.B(d_in[31]));
   XNOR2X1 g2135__4319 (.Y(n_17),
	.A(d_in[5]),
	.B(d_in[37]));
   NOR2BX2 g2__8428 (.Y(n_2),
	.AN(n_64),
	.B(n_78));
   NAND2BX2 g2136__5526 (.Y(n_1),
	.AN(n_64),
	.B(n_77));
   NOR2BX2 g2137__6783 (.Y(n_0),
	.AN(n_64),
	.B(n_75));
endmodule

module rom (
	adr, 
	cs, 
	d_o);
   input [9:0] adr;
   input cs;
   output [31:0] d_o;

   // Internal wires
   wire [38:0] mtrx_out;
   wire [31:0] hdec_out;

   hdec hdec (.d_in({ mtrx_out[38],
		mtrx_out[37],
		mtrx_out[36],
		mtrx_out[35],
		mtrx_out[34],
		mtrx_out[33],
		mtrx_out[32],
		mtrx_out[31],
		mtrx_out[30],
		mtrx_out[29],
		mtrx_out[28],
		mtrx_out[27],
		mtrx_out[26],
		mtrx_out[25],
		mtrx_out[24],
		mtrx_out[23],
		mtrx_out[22],
		mtrx_out[21],
		mtrx_out[20],
		mtrx_out[19],
		mtrx_out[18],
		mtrx_out[17],
		mtrx_out[16],
		mtrx_out[15],
		mtrx_out[14],
		mtrx_out[13],
		mtrx_out[12],
		mtrx_out[11],
		mtrx_out[10],
		mtrx_out[9],
		mtrx_out[8],
		mtrx_out[7],
		mtrx_out[6],
		mtrx_out[5],
		mtrx_out[4],
		mtrx_out[3],
		mtrx_out[2],
		mtrx_out[1],
		1'b0 }),
	.d_out(hdec_out));
   matrix mtrx (.address(adr),
	.data(mtrx_out));
   NOR2BX1 g385__3680 (.Y(d_o[10]),
	.AN(hdec_out[10]),
	.B(cs));
   NOR2BX1 g386__1617 (.Y(d_o[30]),
	.AN(hdec_out[30]),
	.B(cs));
   NOR2BX1 g387__2802 (.Y(d_o[28]),
	.AN(hdec_out[28]),
	.B(cs));
   NOR2BX1 g388__1705 (.Y(d_o[24]),
	.AN(hdec_out[24]),
	.B(cs));
   NOR2BX1 g389__5122 (.Y(d_o[16]),
	.AN(hdec_out[16]),
	.B(cs));
   NOR2BX1 g390__8246 (.Y(d_o[0]),
	.AN(hdec_out[0]),
	.B(cs));
   NOR2BX1 g391__7098 (.Y(d_o[15]),
	.AN(hdec_out[15]),
	.B(cs));
   NOR2BX1 g392__6131 (.Y(d_o[23]),
	.AN(hdec_out[23]),
	.B(cs));
   NOR2BX1 g393__1881 (.Y(d_o[14]),
	.AN(hdec_out[14]),
	.B(cs));
   NOR2BX1 g394__5115 (.Y(d_o[13]),
	.AN(hdec_out[13]),
	.B(cs));
   NOR2BX1 g395__7482 (.Y(d_o[27]),
	.AN(hdec_out[27]),
	.B(cs));
   NOR2BX1 g396__4733 (.Y(d_o[22]),
	.AN(hdec_out[22]),
	.B(cs));
   NOR2BX1 g397__6161 (.Y(d_o[12]),
	.AN(hdec_out[12]),
	.B(cs));
   NOR2BX1 g398__9315 (.Y(d_o[11]),
	.AN(hdec_out[11]),
	.B(cs));
   NOR2BX1 g399__9945 (.Y(d_o[21]),
	.AN(hdec_out[21]),
	.B(cs));
   NOR2BX1 g400__2883 (.Y(d_o[31]),
	.AN(hdec_out[31]),
	.B(cs));
   NOR2BX1 g401__2346 (.Y(d_o[1]),
	.AN(hdec_out[1]),
	.B(cs));
   NOR2BX1 g402__1666 (.Y(d_o[29]),
	.AN(hdec_out[29]),
	.B(cs));
   NOR2BX1 g403__7410 (.Y(d_o[26]),
	.AN(hdec_out[26]),
	.B(cs));
   NOR2BX1 g404__6417 (.Y(d_o[20]),
	.AN(hdec_out[20]),
	.B(cs));
   NOR2BX1 g405__5477 (.Y(d_o[8]),
	.AN(hdec_out[8]),
	.B(cs));
   NOR2BX1 g406__2398 (.Y(d_o[7]),
	.AN(hdec_out[7]),
	.B(cs));
   NOR2BX1 g407__5107 (.Y(d_o[19]),
	.AN(hdec_out[19]),
	.B(cs));
   NOR2BX1 g408__6260 (.Y(d_o[6]),
	.AN(hdec_out[6]),
	.B(cs));
   NOR2BX1 g409__4319 (.Y(d_o[5]),
	.AN(hdec_out[5]),
	.B(cs));
   NOR2BX1 g410__8428 (.Y(d_o[25]),
	.AN(hdec_out[25]),
	.B(cs));
   NOR2BX1 g411__5526 (.Y(d_o[18]),
	.AN(hdec_out[18]),
	.B(cs));
   NOR2BX1 g412__6783 (.Y(d_o[4]),
	.AN(hdec_out[4]),
	.B(cs));
   NOR2BX1 g413__3680 (.Y(d_o[3]),
	.AN(hdec_out[3]),
	.B(cs));
   NOR2BX1 g414__1617 (.Y(d_o[17]),
	.AN(hdec_out[17]),
	.B(cs));
   NOR2BX1 g415__2802 (.Y(d_o[2]),
	.AN(hdec_out[2]),
	.B(cs));
   NOR2BX1 g416__1705 (.Y(d_o[9]),
	.AN(hdec_out[9]),
	.B(cs));
endmodule

